name: 🤝 Update Contributors
on:
  schedule:
    - cron: '0 1 * * *'
  push:
    branches:
      - master
      - next
      - next-major
      - alpha
      - beta
jobs:
  contributors:
    runs-on: ubuntu-latest
    name: A job to automate contributors in readme
    steps:
      - name: Generate Contributors List
        uses: akhilmhdh/contributors-readme-action@v2.3.4
        env:
          GITHUB_TOKEN: ${{ secrets.CONTRIBUTORS_TOKEN }}
